- name: nodejsscan
  # You may pin to the exact commit or the version.
  # uses: ajinabraham/njsscan-action@7237412fdd36af517e2745077cedbf9d6900d711
  uses: ajinabraham/njsscan-action@v6
  with:
    # positional arguments:
  path                  Path can be file(s) or directories with source code

optional arguments:
  -h, --help            show this help message and exit
  --json                set output format as JSON
  --sarif               set output format as SARIF 2.1.0
  --sonarqube           set output format compatible with SonarQube
  -o OUTPUT, --output OUTPUT
                        output filename to save the result
  --missing-controls    enable missing security controls check
  -w, --exit-warning    non zero exit code on warning
  -v, --version         show njsscan version

    args: 
